-- Добавяне на стойности в таблица марки
-- ////////////////////////////

INSERT INTO BIKE_BRANDS
VALUES ('Honda')
		, ('BMW')
		, ('Suzuki')
		, ('Kawasaki')
		, ('Aprilia')
		, ('Ducati')
		, ('Husqvarna')
		, ('KTM')
		, ('Yamaha')

-- Добавяне на стойности в таблица модели
-- ////////////////////////////

INSERT INTO BIKE_MODELS (BRAND_ID, NAME)
VALUES ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'CB')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'CBF')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'CBR')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'Hornet')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'Rebel')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'Shadow')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Honda'), 'VTX')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'BMW'), 'C')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'BMW'), 'F')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'BMW'), 'G')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'BMW'), 'R')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'BMW'), 'S')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Bandit')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Boulevard')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Gsr')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Gsx')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Hayabusa')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Intruder')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Suzuki'), 'Rf')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Kawasaki'), 'CSR')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Kawasaki'), 'Ninja')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Kawasaki'), 'Vulcan')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Kawasaki'), 'Zx')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Kawasaki'), 'Zxr')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Aprilia'), 'Dorsoduro')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Aprilia'), 'Mana')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Aprilia'), 'Pegaso')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Aprilia'), 'RS')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Aprilia'), 'RSV4')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Aprilia'), 'Tuono')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Ducati'), '916')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Ducati'), 'Desmosedici')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Ducati'), 'Monster')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Ducati'), 'Multistrada')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Ducati'), 'Panigale')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Ducati'), 'Streetfighter')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Husqvarna'), 'Nuda')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Husqvarna'), 'FC')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Husqvarna'), 'FE')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Husqvarna'), 'Svartpilen')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Husqvarna'), 'Vitpilen')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Husqvarna'), 'WR')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'KTM'), 'Duke')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'KTM'), 'Enduro')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'KTM'), 'Freeride')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'KTM'), 'SX')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'KTM'), 'Super Duke')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'KTM'), 'Supermoto')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'MT-07')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'MT-09')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'V-Max')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'Virago')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'YZF-R1')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'YZF-R6')
		, ((SELECT ID FROM BIKE_BRANDS WHERE NAME = 'Yamaha'), 'Yz')


-- Добавяне на стойности в таблица типове двигатели
-- ////////////////////////////

INSERT INTO ENGINE_TYPES
VALUES (N'Бензин')
		, (N'Дизел')
		, (N'Етанол')


-- Добавяне на стойности в таблица типове двигатели
-- ////////////////////////////

INSERT INTO COLORS
VALUES (N'бял')
		, (N'жълт')
		, (N'оранжев')
		, (N'червен')
		, (N'зелен')
		, (N'син')
		, (N'бордо')
		, (N'сив')
		, (N'черен')


-- Добавяне на стойности в таблица категория мотоциклети
-- ////////////////////////////

INSERT INTO CATEGORIES
VALUES ('Cafe Racer')
		, (N'Ендуро')
		, (N'Кросов')
		, (N'Пистов')
		, (N'Скутер')
		, (N'СуперМото')
		, (N'Турър')
		, (N'Чопър')


-- Добавяне на стойности в таблица региони
-- ////////////////////////////

INSERT INTO REGIONS
VALUES (N'Благоевград')
		, (N'Бургас')
		, (N'Варна')
		, (N'Велико Търново')
		, (N'Видин')
		, (N'Враца')
		, (N'Габрово')
		, (N'Добрич')
		, (N'Кърджали')
		, (N'Кюстендил')
		, (N'Ловеч')
		, (N'Монтана')
		, (N'Пазарджик')
		, (N'Перник')
		, (N'Плевен')
		, (N'Пловдив')
		, (N'Разград')
		, (N'Русе')
		, (N'Силистра')
		, (N'Сливен')
		, (N'Смолян')
		, (N'София')
		, (N'Стара Загора')
		, (N'Търговище')
		, (N'Хасково')
		, (N'Шумен')
		, (N'Ямбол')
		, (N'Извън страната')


-- Добавяне на стойности в таблица градове
-- ////////////////////////////
INSERT INTO CITIES(REGION_ID, NAME)
VALUES ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Банско')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Белица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Гоце Делчев')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Петрич')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Разлог')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Сандански')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Симитли')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Благоевград'), N'гр. Якоруда')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Айтос')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Ахелой')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Българово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Каблешково')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Камено')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Карнобат')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Несебър')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Обзор')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Поморие')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Приморско')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Свети Влас')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Созопол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Сунгурларе')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Царево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Бургас'), N'гр. Черноморец')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Аксаково')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Белослав')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Бяла')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Вълчи дол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Девня')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Долни чифлик')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Дългопол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Провадия')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Варна'), N'гр. Суворово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Горна Оряховица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Дебелец')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Долна Оряховица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Елена')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Павликени')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Свищов')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Стражица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Велико Търново'), N'гр. Сухиндол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Видин'), N'гр. Белоградчик')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Видин'), N'гр. Брегово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Видин'), N'гр. Кула')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Бяла Слатина')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Козлодуй')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Криводол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Мездра')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Мизия')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Оряхово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Враца'), N'гр. Роман')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Габрово'), N'гр. Дряново')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Габрово'), N'гр. Плачковци')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Габрово'), N'гр. Севлиево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Габрово'), N'гр. Трявна')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Добрич'), N'гр. Балчик')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Добрич'), N'гр. Генерал Тошево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Добрич'), N'гр. Каварна')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Добрич'), N'гр. Тервел')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Добрич'), N'гр. Шабла')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Кърджали'), N'гр. Ардино')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Кърджали'), N'гр. Крумовград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Кърджали'), N'гр. Момчилград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Кюстендил'), N'гр. Бобов дол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Кюстендил'), N'гр. Бобошево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Кюстендил'), N'гр. Сапарева баня')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ловеч'), N'гр. Априлци')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ловеч'), N'гр. Луковит')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ловеч'), N'гр. Тетевен')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ловеч'), N'гр. Троян')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ловеч'), N'гр. Ябланица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Монтана'), N'гр. Берковица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Монтана'), N'гр. Бойчиновци')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Монтана'), N'гр. Вършец')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Монтана'), N'гр. Лом')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Монтана'), N'гр. Чипровци')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Батак')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Брацигово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Велинград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Ветрен')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Костандово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Панагюрище')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Пещера')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Ракитово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Септември')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Стрелча')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пазарджик'), N'гр. Сърница')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Перник'), N'гр. Батановци')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Перник'), N'гр. Брезник')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Перник'), N'гр. Земен')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Перник'), N'гр. Радомир')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Белене')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Гулянци')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Долна Митрополия')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Долни Дъбник')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Кнежа')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Левски')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Никопол')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Тръстеник')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Плевен'), N'гр. Червен бряг')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Асеновград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Баня')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Брезово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Калофер')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Карлово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Кричим')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Куклен')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Лъки')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Перущица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Първомай')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Раковски')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Садово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Сопот')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Стамболийски')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Съединение')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Пловдив'), N'гр. Хисаря')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Разград'), N'гр. Исперих')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Разград'), N'гр. Кубрат')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Разград'), N'гр. Лозница')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Разград'), N'гр. Цар Калоян')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Русе'), N'гр. Бяла')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Русе'), N'гр. Ветово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Русе'), N'гр. Глоджево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Русе'), N'гр. Две могили')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Русе'), N'гр. Мартен')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Русе'), N'гр. Сеново')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Силистра'), N'гр. Главиница')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Силистра'), N'гр. Дулово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Силистра'), N'гр. Тутракан')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Сливен'), N'гр. Кермен')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Сливен'), N'гр. Котел')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Сливен'), N'гр. Нова Загора')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Сливен'), N'гр. Твърдица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Сливен'), N'гр. Шивачево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Смолян'), N'гр. Златоград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Смолян'), N'гр. Мадан')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Смолян'), N'гр. Рудозем')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Смолян'), N'гр. Чепеларе')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Банкя')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Божурище')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Ботевград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Бухово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Годеч')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Долна баня')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Елин Пелин')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Етрополе')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Златица')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Ихтиман')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Костенец')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Костинброд')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Момин проход')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Нови Искър')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Пирдоп')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Самоков')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Своге')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'София'), N'гр. Сливница')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Гурково')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Гълъбово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Казанлък')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Мъглиж')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Николаево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Павел баня')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Раднево')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Чирпан')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Стара Загора'), N'гр. Шипка')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Търговище'), N'гр. Омуртаг')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Търговище'), N'гр. Опака')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Търговище'), N'гр. Попово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Димитровград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Ивайловград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Любимец')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Маджарово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Свиленград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Симеоновград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Тополовград')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Хасково'), N'гр. Харманли')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Шумен'), N'гр. Велики Преслав')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Шумен'), N'гр. Нови пазар')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Шумен'), N'гр. Плиска')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Шумен'), N'гр. Смядово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ямбол'), N'гр. Елхово')
		, ((SELECT ID FROM REGIONS WHERE NAME = N'Ямбол'), N'гр. Стралджа')


-- Добавяне на стойности в таблица потребители
-- ////////////////////////////